name: lean_builder
description: A sample command-line application with basic argument parsing.
version: 0.0.6
publish_to: "none"
# repository: https://github.com/my_org/my_repo

# add executables:
executables:
  lean_builder:



environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  analyzer: ^7.4.4
  _fe_analyzer_shared: ^82.0.0
  xxh3: ^1.2.0
  path: ^1.9.1
  yaml: ^3.1.3
  collection: ^1.18.0
  meta: ^1.12.0
  glob: ^2.1.3
  synchronized:
  dart_style: ^3.0.1
  ansicolor: ^2.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
  test: ^1.25.15

