name: lean_builder
description: A sample command-line application with basic argument parsing.
version: 0.0.5
publish_to: "none"
# repository: https://github.com/my_org/my_repo

# add executables:
executables:
  lean_builder:
  script:



environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
#  flutter:
#    sdk: flutter
#  auto_route:
  args: ^2.7.0
  analyzer: ^7.4.0
  _fe_analyzer_shared: ^81.0.0
  xxh3: ^1.2.0
  path: ^1.9.1
  yaml: ^3.1.3
  collection: ^1.18.0
  synchronized:
  gen_benchmark:
    path: ../gen_benchmark



dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
  test: ^1.25.15

