name: code_genie
description: A sample command-line application with basic argument parsing.
version: 0.0.3
publish_to: "none"
# repository: https://github.com/my_org/my_repo

# add executables:
executables:
  code_genie:



environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
#  flutter:
#    sdk: flutter
#  auto_route:
  args: ^2.7.0
  analyzer: ^7.3.0
  _fe_analyzer_shared: ^80.0.0
  xxh3: ^1.2.0
  path: ^1.9.1
  yaml: ^3.1.3
  collection: ^1.18.0
#  mofad_dashboard:
#    path: ../mofad_dashboard
#
#dependency_overrides:
#  intl: ^0.18.1


dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

